package input;

import java.awt.*;
import java.awt.event.*;

/**
 * Basic mouse listener
 * 
 * @author Deal With It Productions
 * @version 0.1
 */
public class Mouse extends MouseAdapter
{
	private int x, y; //Click coordiantes
	private boolean clicked; //whether the last mouse click has been handled
	
	/**
	 * Constructor that sets coordinates to 0 and the mouse to an unclicked state
	 */
	public Mouse()
	{
		x = 0;
		y = 0;
		
		clicked = false;
	}
	
	/**
	 * Get the position of the last click.
	 * @return A Point of the last click location if it has not been handled yet; otherwise null
	 */
	public Point getPos()
	{
		if(!clicked) //If the last click has been handled
			return null;
		
		clicked = false; //Set the click to handled
		return new Point(x, y);
	}
	
	/**
	 * Overriding the default method to register mouse clicks (press and release)
	 * 
	 * @param e The mouse event generated by a mouse click
	 */
	public void mouseClicked(MouseEvent e)
	{
		x = e.getX();
		y = e.getY();
		
		clicked = true; //The click is waiting to be handled
	}
	
}
